// LinkedIn Presence Manager - Core Types
// Generated by Senior CTO/PM with 20+ years experience

// ============================================
// USER & AUTH TYPES
// ============================================

export type AccountType = 'individual' | 'company' | 'agency' | 'admin';
export type OnboardingStep = 
  | 'welcome' 
  | 'account_type' 
  | 'profile_setup' 
  | 'linkedin_connect' 
  | 'workspace_setup'
  | 'completed';

export interface User {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  avatarUrl: string | null;
  phone: string | null;
  accountType: AccountType;
  isEmailVerified: boolean;
  isActive: boolean;
  onboardingCompleted: boolean;
  onboardingStep: string | null;
  lastLoginAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
}

// ============================================
// ORGANIZATION & WORKSPACE TYPES
// ============================================

export type OrganizationRole = 'owner' | 'admin' | 'member' | 'viewer';
export type WorkspaceRole = 'owner' | 'admin' | 'editor' | 'viewer';
export type OrganizationType = 'company' | 'agency';
export type WorkspaceType = 'personal' | 'company' | 'client';

export interface Organization {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  logoUrl: string | null;
  website: string | null;
  orgType: OrganizationType;
  settings: Record<string, unknown> | null;
  planType: PlanType;
  planLimits: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface OrganizationMember {
  id: string;
  organizationId: string;
  userId: string;
  role: OrganizationRole;
  permissions: Record<string, unknown> | null;
  invitationStatus: 'pending' | 'accepted' | 'declined';
  invitedBy: string | null;
  invitedAt: Date | null;
  joinedAt: Date;
  user?: User;
}

export interface Workspace {
  id: string;
  organizationId: string;
  name: string;
  slug: string;
  description: string | null;
  iconUrl: string | null;
  workspaceType: WorkspaceType;
  agencyClientId: string | null;
  settings: Record<string, unknown> | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  organization?: Organization;
  linkedinProfile?: LinkedInProfileDraft;
  linkedinPages?: LinkedInPageDraft[];
}

export interface WorkspaceMember {
  id: string;
  workspaceId: string;
  userId: string;
  role: WorkspaceRole;
  permissions: Record<string, unknown> | null;
  joinedAt: Date;
  user?: User;
}

// ============================================
// LINKEDIN PROFILE TYPES
// ============================================

export type ProfileStatus = 'draft' | 'ready' | 'published';
export type EmploymentType = 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship' | 'other';
export type LocationType = 'on-site' | 'hybrid' | 'remote';
export type LanguageProficiency = 'elementary' | 'limited' | 'professional' | 'full_professional' | 'native';

export interface LinkedInProfileDraft {
  id: string;
  workspaceId: string;
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  photoUrl: string | null;
  bannerUrl: string | null;
  location: string | null;
  countryCode: string | null;
  postalCode: string | null;
  industryId: string | null;
  industryName: string | null;
  summary: string | null;
  websiteUrl: string | null;
  linkedinUrl: string | null;
  twitterHandle: string | null;
  profileScore: number;
  completionRate: number;
  status: ProfileStatus;
  publishedAt: Date | null;
  generatedFields: string[] | null;
  suggestions: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
  experiences?: ExperienceEntry[];
  educations?: EducationEntry[];
  skills?: ProfileSkill[];
  certifications?: Certification[];
  projects?: ProjectEntry[];
  services?: ServiceEntry[];
  languages?: ProfileLanguage[];
}

export interface ExperienceEntry {
  id: string;
  profileDraftId: string;
  title: string;
  company: string;
  companyId: string | null;
  companyLogoUrl: string | null;
  employmentType: EmploymentType | null;
  location: string | null;
  locationType: LocationType | null;
  startDate: Date | null;
  endDate: Date | null;
  current: boolean;
  description: string | null;
  isAIGenerated: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface EducationEntry {
  id: string;
  profileDraftId: string;
  school: string;
  schoolId: string | null;
  schoolLogoUrl: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: Date | null;
  endDate: Date | null;
  description: string | null;
  isAIGenerated: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProfileSkill {
  id: string;
  profileDraftId: string;
  name: string;
  skillId: string | null;
  endorsements: number;
  isAISuggested: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Certification {
  id: string;
  profileDraftId: string;
  name: string;
  authority: string | null;
  authorityId: string | null;
  authorityLogoUrl: string | null;
  licenseNumber: string | null;
  displayOnProfile: boolean;
  issueDate: Date | null;
  expirationDate: Date | null;
  doesNotExpire: boolean;
  credentialUrl: string | null;
  isAIGenerated: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectEntry {
  id: string;
  profileDraftId: string;
  title: string;
  description: string | null;
  projectUrl: string | null;
  startDate: Date | null;
  endDate: Date | null;
  current: boolean;
  experienceId: string | null;
  isAIGenerated: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ServiceEntry {
  id: string;
  profileDraftId: string;
  name: string;
  description: string | null;
  isAIGenerated: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProfileLanguage {
  id: string;
  profileDraftId: string;
  language: string;
  proficiency: LanguageProficiency | null;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// LINKEDIN PAGE TYPES
// ============================================

export type PageType = 'company' | 'showcase' | 'educational';
export type PageStatus = 'draft' | 'ready' | 'published';
export type CompanySize = '1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1001-5000' | '5001-10000' | '10001+';
export type CompanyType = 'public' | 'private' | 'nonprofit' | 'government' | 'partnership' | 'self_employed';
export type PageAdminRole = 'admin' | 'analyst' | 'content_admin';

export interface LinkedInPageDraft {
  id: string;
  organizationId: string;
  workspaceId: string | null;
  name: string;
  publicUrl: string | null;
  tagline: string | null;
  logoUrl: string | null;
  bannerUrl: string | null;
  description: string | null;
  website: string | null;
  industryId: string | null;
  industryName: string | null;
  companySize: CompanySize | null;
  companyType: CompanyType | null;
  foundedYear: number | null;
  headquarters: string | null;
  locations: Record<string, unknown>[] | null;
  specialties: string[] | null;
  ctaType: string | null;
  ctaUrl: string | null;
  pageType: PageType;
  parentPageId: string | null;
  status: PageStatus;
  linkedinPageId: string | null;
  publishedAt: Date | null;
  profileScore: number;
  completionRate: number;
  generatedFields: string[] | null;
  suggestions: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
  pageAdmins?: PageAdmin[];
  products?: PageProduct[];
}

export interface PageAdmin {
  id: string;
  pageDraftId: string;
  userId: string | null;
  linkedinConnectionId: string | null;
  name: string;
  email: string | null;
  role: PageAdminRole;
  status: 'pending' | 'active' | 'removed';
  createdAt: Date;
  updatedAt: Date;
}

export interface PageProduct {
  id: string;
  pageDraftId: string;
  name: string;
  description: string | null;
  imageUrl: string | null;
  productUrl: string | null;
  category: string | null;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// CONTENT TYPES
// ============================================

export type PostType = 'text' | 'image' | 'carousel' | 'video' | 'article' | 'poll';
export type PostCategory = 
  | 'thought_leadership' 
  | 'company_update' 
  | 'product_announcement' 
  | 'hiring' 
  | 'employer_branding' 
  | 'industry_insight' 
  | 'educational' 
  | 'personal_story'
  | 'other';
export type PostStatus = 'draft' | 'scheduled' | 'published' | 'failed';
export type ContentTone = 'professional' | 'casual' | 'inspirational' | 'educational' | 'promotional';

export interface ContentPost {
  id: string;
  userId: string | null;
  organizationId: string | null;
  workspaceId: string | null;
  postType: PostType;
  postCategory: PostCategory | null;
  title: string | null;
  content: string;
  hooks: string[] | null;
  mediaUrls: string[] | null;
  mediaType: string | null;
  carouselSlides: CarouselSlide[] | null;
  targetAudience: string | null;
  targetIndustry: string | null;
  targetRole: string | null;
  tone: ContentTone | null;
  language: string;
  aiPrompt: string | null;
  aiModel: string | null;
  isAIGenerated: boolean;
  status: PostStatus;
  scheduledFor: Date | null;
  publishedAt: Date | null;
  publishedUrl: string | null;
  linkedinPostId: string | null;
  publishToProfile: boolean;
  publishToPageId: string | null;
  likes: number;
  comments: number;
  shares: number;
  impressions: number;
  templateId: string | null;
  calendarId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CarouselSlide {
  order: number;
  title: string;
  content: string;
  imageUrl?: string;
  mediaUrl?: string;
}

export interface ContentCalendar {
  id: string;
  userId: string | null;
  organizationId: string | null;
  workspaceId: string | null;
  name: string;
  description: string | null;
  startDate: Date;
  endDate: Date | null;
  postingDays: number[] | null;
  postingTimes: string[] | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Template {
  id: string;
  userId: string | null;
  organizationId: string | null;
  name: string;
  description: string | null;
  category: string | null;
  content: string;
  variables: TemplateVariable[] | null;
  isPublic: boolean;
  isPremium: boolean;
  usageCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface TemplateVariable {
  name: string;
  type: 'text' | 'number' | 'date' | 'select';
  required: boolean;
  defaultValue?: string;
  options?: string[];
  description?: string;
}

// ============================================
// ANALYTICS TYPES
// ============================================

export type EntityType = 'profile' | 'page' | 'post';

export interface AnalyticsSnapshot {
  id: string;
  userId: string | null;
  organizationId: string | null;
  workspaceId: string | null;
  snapshotDate: Date;
  entityType: EntityType;
  entityId: string | null;
  profileViews: number;
  searchAppearances: number;
  connections: number;
  followers: number;
  postsCreated: number;
  totalImpressions: number;
  totalEngagement: number;
  avgEngagementRate: number | null;
  pageViews: number;
  uniqueVisitors: number;
  customMetrics: Record<string, unknown> | null;
  createdAt: Date;
}

export interface ProfileScore {
  overall: number;
  breakdown: {
    photo: number;
    headline: number;
    summary: number;
    experience: number;
    education: number;
    skills: number;
    certifications: number;
    recommendations: number;
  };
  suggestions: ProfileSuggestion[];
}

export interface ProfileSuggestion {
  field: string;
  priority: 'high' | 'medium' | 'low';
  message: string;
  action: string;
}

// ============================================
// BILLING TYPES
// ============================================

export type PlanType = 'free' | 'pro' | 'business' | 'agency';
export type SubscriptionStatus = 'active' | 'past_due' | 'canceled' | 'expired';
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';
export type PaymentStatus = 'pending' | 'succeeded' | 'failed' | 'refunded';

export interface Plan {
  id: string;
  name: string;
  type: PlanType;
  price: number;
  currency: string;
  interval: 'month' | 'year';
  features: string[];
  limits: PlanLimits;
  isPopular?: boolean;
}

export interface PlanLimits {
  workspaces: number;
  profiles: number;
  pages: number;
  postsPerMonth: number;
  aiGenerationsPerMonth: number;
  teamMembers: number;
  clients: number;
  templates: number;
  mediaStorage: number; // in MB
  analyticsHistory: number; // in days
}

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    type: 'free',
    price: 0,
    currency: 'EUR',
    interval: 'month',
    features: [
      '1 personal workspace',
      '1 LinkedIn profile',
      '5 posts per month',
      '10 AI generations per month',
      'Basic analytics',
      '7 days analytics history',
    ],
    limits: {
      workspaces: 1,
      profiles: 1,
      pages: 0,
      postsPerMonth: 5,
      aiGenerationsPerMonth: 10,
      teamMembers: 1,
      clients: 0,
      templates: 5,
      mediaStorage: 50,
      analyticsHistory: 7,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    type: 'pro',
    price: 29,
    currency: 'EUR',
    interval: 'month',
    features: [
      '3 workspaces',
      '3 LinkedIn profiles',
      '1 company page',
      '50 posts per month',
      '100 AI generations per month',
      'Advanced analytics',
      '30 days analytics history',
      'Priority support',
    ],
    limits: {
      workspaces: 3,
      profiles: 3,
      pages: 1,
      postsPerMonth: 50,
      aiGenerationsPerMonth: 100,
      teamMembers: 1,
      clients: 0,
      templates: 25,
      mediaStorage: 500,
      analyticsHistory: 30,
    },
    isPopular: true,
  },
  {
    id: 'business',
    name: 'Business',
    type: 'business',
    price: 79,
    currency: 'EUR',
    interval: 'month',
    features: [
      '10 workspaces',
      '10 LinkedIn profiles',
      '5 company pages',
      'Unlimited posts',
      '500 AI generations per month',
      'Team collaboration (5 members)',
      'Advanced analytics',
      '90 days analytics history',
      'API access',
    ],
    limits: {
      workspaces: 10,
      profiles: 10,
      pages: 5,
      postsPerMonth: -1, // unlimited
      aiGenerationsPerMonth: 500,
      teamMembers: 5,
      clients: 0,
      templates: 100,
      mediaStorage: 2000,
      analyticsHistory: 90,
    },
  },
  {
    id: 'agency',
    name: 'Agency',
    type: 'agency',
    price: 199,
    currency: 'EUR',
    interval: 'month',
    features: [
      'Unlimited workspaces',
      'Unlimited LinkedIn profiles',
      'Unlimited company pages',
      'Unlimited posts',
      'Unlimited AI generations',
      'Unlimited team members',
      'Unlimited clients',
      'White-label option',
      'Priority support',
      'API access',
      'Custom integrations',
    ],
    limits: {
      workspaces: -1,
      profiles: -1,
      pages: -1,
      postsPerMonth: -1,
      aiGenerationsPerMonth: -1,
      teamMembers: -1,
      clients: -1,
      templates: -1,
      mediaStorage: 10000,
      analyticsHistory: 365,
    },
  },
];

export interface Subscription {
  id: string;
  userId: string | null;
  organizationId: string | null;
  planId: string;
  planName: string;
  planType: PlanType;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  stripePriceId: string | null;
  interval: 'month' | 'year' | null;
  intervalCount: number;
  amount: number;
  currency: string;
  status: SubscriptionStatus;
  trialEndsAt: Date | null;
  currentPeriodStart: Date | null;
  currentPeriodEnd: Date | null;
  cancelAtPeriodEnd: boolean;
  limits: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Invoice {
  id: string;
  userId: string | null;
  organizationId: string | null;
  subscriptionId: string | null;
  stripeInvoiceId: string | null;
  invoiceNumber: string | null;
  amount: number;
  currency: string;
  taxAmount: number | null;
  status: InvoiceStatus;
  issuedAt: Date | null;
  dueAt: Date | null;
  paidAt: Date | null;
  pdfUrl: string | null;
  hostedUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// NOTIFICATION TYPES
// ============================================

export type NotificationType = 'info' | 'warning' | 'success' | 'error';

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  actionUrl: string | null;
  actionText: string | null;
  isRead: boolean;
  readAt: Date | null;
  createdAt: Date;
}

// ============================================
// API RESPONSE TYPES
// ============================================

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  meta?: {
    page?: number;
    limit?: number;
    total?: number;
    hasMore?: boolean;
  };
}

export interface PaginatedResponse<T> {
  items: T[];
  page: number;
  limit: number;
  total: number;
  hasMore: boolean;
}

// ============================================
// FORM TYPES
// ============================================

export interface LoginForm {
  email: string;
  password: string;
  remember?: boolean;
}

export interface RegisterForm {
  email: string;
  password: string;
  confirmPassword: string;
  firstName: string;
  lastName: string;
  accountType: AccountType;
  acceptTerms: boolean;
}

export interface ProfileForm {
  firstName: string;
  lastName: string;
  headline: string;
  location: string;
  industryId: string;
  industryName: string;
  summary: string;
  websiteUrl: string;
  twitterHandle: string;
}

export interface ExperienceForm {
  title: string;
  company: string;
  employmentType: EmploymentType;
  location: string;
  locationType: LocationType;
  startDate: string;
  endDate: string | null;
  current: boolean;
  description: string;
}

export interface EducationForm {
  school: string;
  degree: string;
  fieldOfStudy: string;
  startDate: string;
  endDate: string | null;
  description: string;
}

export interface PostForm {
  postType: PostType;
  postCategory: PostCategory;
  title: string;
  content: string;
  mediaUrls: string[];
  tone: ContentTone;
  language: string;
  scheduledFor: string | null;
  publishToProfile: boolean;
  publishToPageId: string | null;
}
